<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <!-- Nested Row within Card Body -->
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Logar</h1>
                  </div>
                  <form action="/admin/logar_admin" class="logar" method="POST">
                    <div class="form-group">
                      <input name="email" type="text" class="form-control form-control-user" id="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                      <input name="senha" type="password" class="form-control form-control-user" id="senha" placeholder="Senha" required>
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-user btn-block">Logar</button>
                  </form>
                  <hr>
                  
                </div>
              
          </div>
        </div>

      </div>

    </div>

</div>