<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Begin Page Content -->
        <div class="container-fluid">
            <h1 class="h3 mb-2 text-gray-800 clearfix">Cadastrar Produto</h1>

            <?php
            if (isset($this->view->campos_obrigatorios) && $this->view->campos_obrigatorios == 'true') {
            ?>
                <p class="text-danger">Campos obrigatorios não preenchidos</p>
            <?php
            } else if ($this->view->campos_obrigatorios == 'false') {
            ?>
                <p class="text-success">Cadastrado com sucesso</p>
            <?php
            }
            ?>
            <form action="/admin/cadastra_produto" method="POST" enctype="multipart/form-data">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="nome">Nome</label>
                        <input name="nome" type="text" class="form-control" id="nome-produto" placeholder="Nome" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="descricao">Descrição</label>
                        <input name="descricao" type="text" class="form-control" id="descricao-produto" placeholder="Descrição">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="preco">Preço</label>
                        <input name="preco" type="text" class="form-control" id="preco-produto" placeholder="Preço" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="quantidade">Quantidade</label>
                        <input name="quantidade" type="text" class="form-control" id="quantidade-produto" placeholder="Quantidade" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <select name="categoria" class="custom-select resultado" required>
                            <option selected>Categoria</option>
                            <?php
                            foreach ($this->view->categorias as $idx_sub => $categoria) {
                            ?>
                                <option value="<?= $categoria['id']; ?>"><?= $categoria['nome']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <select name="subcategoria" class="custom-select resultado" required>
                            <option selected>Subcategoria</option>
                            <?php
                            foreach ($this->view->subcategorias as $idx_sub => $subcategoria) {
                            ?>
                                <option value="<?= $subcategoria['id']; ?>"><?= $subcategoria['nome']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <input name="arquivo" type="file" class="custom-file-input" id="file-produto">
                        <label class="custom-file-label" for="file">Escolha um arquivo...</label>
                    </div>
                </div>
                <button type="submit" name="enviar-formulario" class="btn btn-primary mt-3">Salvar</button>
                <a type="submit" href="/admin/produtos" class="btn btn-secondary mt-3">Cancelar</a>
            </form>
        </div>
        <!-- End begin page content -->
    </div>
    <!-- End of Content Wrapper -->