	<!-- Start Product Area -->
    <div class="product-area section">
            <div class="container">
				<div class="row">
					<div class="col-12">
						<div class="section-title">
							<h2>Produtos</h2>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="product-info">
							<div class="tab-content" id="myTabContent">
								<!-- Start Single Tab -->
								<div class="tab-pane fade show active" id="man" role="tabpanel">
									<div class="tab-single">
										<div class="row">
											<?php foreach($this->view->produtos as $id_produto => $produto){ ?>
											<div class="col-xl-3 col-lg-4 col-md-4 col-12">
												<div class="single-product">
													<div class="product-img">
														<a href="/produto?id=<?= $produto['id'] ?>">
															<img class="default-img" src="./img_produtos/<?= $produto['imagem'] ?>">														
														</a>
														<div class="button-head">
															<div class="product-action">
																
															</div>
															<div class="product-action-2">
																
															</div>
														</div>
													</div>
													<div class="product-content">
														<h3><a href="/produto?id=<?= $produto['id'] ?>"><?= $produto['nome'] ?></a></h3>
														<div class="product-price">
															<span><?= $produto['valor'] ?></span>
														</div>
													</div>
												</div>
											</div>
											<?php } ?>
										</div>
									</div>
								</div>
								<!--/ End Single Tab -->
							</div>
						</div>
					</div>
					<?php 
					?>
					<div class="col-12">
						<nav aria-label="Page navigation example">
							<ul class="pagination">
								<li class="page-item"><a class="page-link" href="?pagina=1
								<?php
									if(isset($_GET['categoria']) && isset($_GET['subcategoria'])){
										echo '&categoria='.$_GET['categoria'].'&subcategoria='.$_GET['subcategoria'];
									} else if(isset($_GET['pesquisa']) && isset($_GET['categoria']) && $_GET['categoria'] != ' '){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.$_GET['categoria'];
									} else if(isset($_GET['categoria']) && $_GET['categoria'] != ' '){
										echo '&categoria='.$_GET['categoria'];
									} else if(isset($_GET['pesquisa'])){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.'+';
									}
								 ?>">Previous</a></li>
								<?php for($i = 1; $i <= $this->view->total_de_paginas; $i++){ ?>
								<li class="page-item"><a class="page-link" style="background-color: <?= $this->view->pagina_ativa == $i ? '#F7941D' : '' ?>;" href="?pagina=<?= $i ?>
								<?php 
									if(isset($_GET['categoria']) && isset($_GET['subcategoria'])){
										echo '&categoria='.$_GET['categoria'].'&subcategoria='.$_GET['subcategoria'];
									} else if(isset($_GET['pesquisa']) && isset($_GET['categoria']) && $_GET['categoria']  != ' '){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.$_GET['categoria'];
									} else if(isset($_GET['categoria']) && $_GET['categoria'] != ' '){
										echo '&categoria='.$_GET['categoria'];
									} else if(isset($_GET['pesquisa'])){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.'+';
									}
								 ?>"><?= $i ?></a></li>
								<?php } ?>
								<li class="page-item"><a class="page-link" href="?pagina=<?= $this->view->total_de_paginas ?>
								<?php 
									if(isset($_GET['categoria']) && isset($_GET['subcategoria'])){
										echo '&categoria='.$_GET['categoria'].'&subcategoria='.$_GET['subcategoria'];
									} else if(isset($_GET['pesquisa']) && isset($_GET['categoria']) && $_GET['categoria'] != ' '){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.$_GET['categoria'];
									} else if(isset($_GET['categoria']) && $_GET['categoria'] != ' '){
										echo '&categoria='.$_GET['categoria'];
									} else if(isset($_GET['pesquisa'])){
										echo '&pesquisa='.$_GET['pesquisa'].'&categoria='.'+';
									}
									
								?>">Next</a></li>
							</ul>
						</nav>
					</div>
				</div>
            </div>
    </div>
	<!-- End Product Area -->