		<!-- Breadcrumbs -->
		<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
								<li class="disabled"><a href="#">cadastrar</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
				
		<!-- Start Checkout -->
		<section class="shop checkout section">
			<div class="container">
				<div class="row"> 
					<div class="col-lg-8 col-12">
						<div class="checkout-form">
							<h2>Registrar-se</h2>
							<!-- Form -->
							<form class="form" action="/registrar" method="post">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12">
										<?php if($this->view->erroCadastro) { ?>
											<small class="form-text text-danger"> Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
										<?php } ?>
									</div>
								</div>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Nome<span>*</span></label>
											<input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" placeholder="Nome" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Sobrenome<span>*</span></label>
											<input type="text" value="<?= $this->view->usuario['sobrenome'] ?>" name="sobrenome" placeholder="Sobrenome" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Email<span>*</span></label>
											<input type="email" value="<?= $this->view->usuario['email'] ?>" name="email" placeholder="Email" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>CPF<span>*</span></label>
											<input type="text" value="<?= $this->view->usuario['cpf'] ?>" name="cpf" placeholder="CPF" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Senha<span>*</span></label>
											<input type="password" name="senha" placeholder="Senha" required="required">
										</div>
										
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Confirmar Senha<span>*</span></label>
											<input type="password" name="conf-senha" placeholder="Confirmar Senha" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
									</div>
										
								</div>
							</form>
							<!--/ End Form -->
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Checkout -->
		