		<!-- Breadcrumbs -->
		<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
								<li class="active"><a href="#">Logar</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
				
		<!-- Start Checkout -->
		<section class="shop checkout section">
			<div class="container">
				<div class="row"> 
					<div class="col-lg-8 col-12">
						<div class="checkout-form">
							<h2>Logar</h2><br>
							<!-- Form -->
							<form class="form" action="/logar" method="post">
								<?php if($this->view->login == 'erro') { ?>
								<div class="row ml-0">
									<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
								</div>
								<?php } ?>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Email<span>*</span></label>
											<input type="email" name="email" placeholder="Email" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Senha<span>*</span></label>
											<input type="password" name="senha" placeholder="Senha" required="required">
										</div>
										
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<button type="submit" class="btn btn-primary btn-block">Logar</button>
									</div>
										
								</div>
							</form>
							<!--/ End Form -->
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Checkout -->
		