		<!-- Breadcrumbs -->
		<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
								<li class="active"><a href="#">Produto</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
			
		<!-- Start Blog Single -->
		<section class="blog-single section">
			<div class="container">
				
				<div class="row">
					
					<div class="col-lg-8 col-12">
						<div class="blog-single-main">
							
							<div class="row">
								<div class="col-12">
									
									<div class="image">
										<img src="imagensp/<?= $this->view->produtos['imagem'] ?>" alt="#">
									</div>
									<div class="blog-detail">
										<h2 class="blog-title">Descrição</h2>
										<div class="blog-meta">
											<span class="author"><a href="#"><i class="fa fa-calendar"></i>Dec 24, 2018</a></span>
										</div>
										<div class="content">
											<p><?= $this->view->produtos['descricao'] ?></p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-12">
						<div class="main-sidebar">
							<h2 class=""><?= $this->view->produtos['nome'] ?></h2>

							<hr>

							<h4 class="price">
								<span class="product-price">
									<bdi>
										<span>R$</span>
										<?= $this->view->produtos['valor'] ?>
									</bdi>
								</span>
							</h4>
						
							<div class="form-produto">
								<form class="form-tamanho-camisa form-group row" method="post" action="/add_carrinho">
									<input type="hidden" name="id_produto" value="<?= $_GET['id'] ?>">
									<input type="hidden" name="valor_unit" value="<?= $this->view->produtos['valor'] ?>">
									<?php 
										if(isset($_GET['errorCampos']) && $_GET['errorCampos'] == 'true'){
									?>
									<p class="text-danger">Campos não preenchidos ou invalidos</p>
									<?php } ?>
									<div class="form-check form-check-inline">
										<label class="form-check-label">
											<input type="radio" id="PP" class="form-check-input" name="tamanho-camisa" value="PP"> PP
										</label>
									</div>
									<div class="form-check form-check-inline">
										<label class="form-check-label">
											<input type="radio" id="P" class="form-check-input" name="tamanho-camisa" value="P"> P
										</label>
									</div>
									<div class="form-check form-check-inline">
										<label class="form-check-label">
											<input type="radio" id="M" class="form-check-input" name="tamanho-camisa" value="M"> M
										</label>
									</div>
									<div class="form-check form-check-inline">
										<label class="form-check-label">
											<input type="radio" id="G" class="form-check-input" name="tamanho-camisa" value="G"> G
										</label>
									</div>

									<div class="form-group row">
									<div class="col-6">
										<label for="inputPassword6" class="col-form-label">Quantidade:</label>
										<input class="form-control" type="number" name="quantidade" value="1" id="example-number-input">
									</div>
									</div>
									
									

									<button type="submit" class="btn">Adicionar ao carrinho</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Blog Single -->