		<!-- Breadcrumbs -->
		<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
								<li class="active"><a href="#">Produto</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
			
		<!-- Start Blog Single -->
		<section class="blog-single section">
			<div class="container">
				
				<div class="row">
					
					<div class="col-lg-8 col-12">
						<div class="blog-single-main">
							
							<div class="row">
								<div class="col-12">
									
									<div class="image">
										<img src="imagensp/<?= $this->view->produtos['imagem'] ?>" alt="#">
									</div>
									<div class="blog-detail">
										<h2 class="blog-title">Descrição</h2>
										<div class="blog-meta">
											<span class="author"><a href="#"><i class="fa fa-calendar"></i>Dec 24, 2018</a></span>
										</div>
										<div class="content">
											<p><?= $this->view->produtos['descricao'] ?></p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-12">
						<div class="main-sidebar">
							<h2><?= $this->view->produtos['nome'] ?></h2>
							<div class="button-head">
								<div class="product-action">
									<a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Adicionar ao carrinho</span></a>			
								</div>
							</div>


							<h4 class="price">
								<span class="product-price">
									<bdi>
										<span>R$</span>
										<?= $this->view->produtos['valor'] ?>
									</bdi>
								</span>
							</h4>

							<form class="form-tamanro-camisa" action="">
								<input type="radio" id="PP" class="tamanho-camisa" name="tamanho-camisa" value="PP">
								<label for="PP">PP</label><br>
								<input type="radio" id="P" class="tamanho-camisa" name="tamanho-camisa" value="P">
								<label for="P">P</label><br>
								<input type="radio" id="M" class="tamanho-camisa" name="tamanho-camisa" value="M">
								<label for="M">M</label><br>
								<input type="radio" id="G" class="tamanho-camisa" name="tamanho-camisa" value="G">
								<label for="G">G</label><br>

								<button type="submit" class="btn">Adicionar ao carrinho</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Blog Single -->