	<!-- Breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
							<li class="active"><a href="#">Cart</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->
			
	<!-- Shopping Cart -->
	<div class="shopping-cart section">
		<div class="container">
			<?php if($this->view->itens){ ?>
			<div class="row">
			
				<div class="col-12">
					
					<!-- Shopping Summery -->
					<table class="table shopping-summery">
						<thead>
							<tr class="main-hading">
								<th>PRODUTO</th>
								<th>NOME</th>
								<th>TAMANHO</th>
								<th class="text-center">PREÇO UNITARIO</th>
								<th class="text-center">QUANTIDADE</th>
								<th class="text-center">TOTAL</th> 
								<th class="text-center"><i class="ti-trash remove-icon"></i></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->view->itens as $id_item => $item){ 
								$trasportadora = $item['transportadora'];
								$endereco = $item['endereco'];
								?>

							<tr>
								<td class="image" data-title="No"><img src="./img_produtos/<?= $item['imagem'] ?>" alt="#"></td>
								<td class="product-des" data-title="Description">
									<p class="product-name"><a href="/produto?id=<?= $item['id_produtos'] ?>"><?= $item['nome'] ?></a></p>
								</td>
								<td class="tamanho" data-title="Tamanho"><span><?= $item['tamanho'] ?></span></td>
								<td class="price" data-title="Price"><span><?= $item['valor'] ?></span></td>
								<td class="qty" data-title="Qty"><span><?= $item['quantidade'] ?></span></td>
								<td class="total-amount" data-title="Total"><span><?= $item['total'] ?></span></td>
								<td class="action" data-title="Remove"><a href="/remove-item?id=<?= $item['id'] ?>"><i class="ti-trash remove-icon"></i></a></td>
							</tr>	
							<?php } ?>					
						</tbody>
					</table>
					<!--/ End Shopping Summery -->
				</div>
			</div>
				<div class="row">
					<div class="col-12">
						<!-- Total Amount -->
						<div class="total-amount">
							<div class="row">
								<div class="col-lg-8 col-md-5 col-12">
									<!-- Transportadora -->
									<div class="left">
										<div class="transportadora">
											<form action="#" target="_blank">
												<label> Selecione a transportadora: </label><br>
												<select id="transportadoras" onchange="location = this.value;">
												<?php foreach($this->view->transportadoras as $id_item => $item){ 
													if($item['id'] == $trasportadora){
												?>	
													<option selected value="/transportadora?id=<?= $item['id']; ?>">
													<?php 
														echo '<pre>';
														print_r($item['nome'].' - '.$item['tempo_entrega']. ' - R$'. $item['valor']);
														echo '</pre>';
													?>
													</option>
													
												<?php } else { ?>

													<option value="/transportadora?id=<?= $item['id']; ?>">
													<?php 
														echo '<pre>';
														print_r($item['nome'].' - '.$item['tempo_entrega']. ' - R$'. $item['valor']);
														echo '</pre>';
													?>
													</option>
												
												<?php }} ?>
												</select>
											</form>
										</div>
									</div>

									<div class="left endereco">
										<div class="transportadora">
											<form action="#" target="_blank">

												<label> Selecione o endereço de entrega: </label><br>
												<select id="endereco" onchange="location = this.value;">
												<option selected disabled value="">---</option>
												<?php foreach($this->view->enderecos as $id_item => $item){ 
													if($item['id'] == $endereco){
												?>	
													<option selected value="/endereco?id=<?= $item['id']; ?>">
													<?php 
														$id_endereco = $item['id'];
														echo '<pre>';
														print_r($item['rua'].', '.$item['numero']. ' - '. $item['bairro'] . ', ' . $item['cidade'] . ' - ' . $item['estado']);
														echo '</pre>';
													?>
													</option>
													
												<?php } else { ?>
													<option value="/endereco?id=<?= $item['id']; ?>">
													<?php 
														echo '<pre>';
														print_r($item['rua'].', '.$item['numero']. ' - '. $item['bairro'] . ', ' . $item['cidade'] . ' - ' . $item['estado']);
														echo '</pre>';
													?>
													</option>
												
												<?php }} ?>
												</select>
												
											</form>
										</div>
										<div class="col-lg-12 col-md-6 col-12">
											<?php if(isset($_GET['empty_endereco']) && $_GET['empty_endereco'] == 'true') { ?>
												<small class="form-text text-danger"> Por favor selecione o endereço.</small>
											<?php } ?>
											</div>
									</div>
								</div>
								<div class="col-lg-4 col-md-7 col-12">
									<div class="right">
										<?php foreach($this->view->total_carrinho as $id_item => $item){ ?>
										<ul>
											<li>Total carrinho<span>R$ <?= $item['total_carrinho'] ?></span></li>
											<li>Frete<span>R$ <?= $item['frete'] ?></span></li>
											<li class="last">Total da compra<span>R$ <?= $item['total'] ?></span></li>
										</ul>
										<?php } ?>
										<div class="button5">
											<a href="/confirma_endereco?id_endereco=<?php if(isset($id_endereco)){ echo $id_endereco; }else{ echo ''; } ?>" class="btn">Finalizar compra</a>
											<a href="/" class="btn">Voltar a comprar</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!--/ End Total Amount -->
					</div>
				</div>
				<?php } else { ?>
						<div class="sem-itens-carrinho">
							<h1>Não há itens no carrinho</h1>
						</div>
						<?php } ?>
		</div>
	</div>
	<!--/ End Shopping Cart -->