<!-- Breadcrumbs -->
<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
							<li class="disabled"><a href="blog-single.html">cadastrar</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->
			
	<!-- Start Checkout -->
	<section class="shop checkout section">
		<div class="container">
			<div class="row"> 
				<div class="checkout-form">
					<h2>Compra realizada com sucesso</h2>
					<p>Clique para ver os pedidos ou voltar a página home</p>

					<a class="btn btn-primary btn-block text-white text-center" href="/pedido_usuario">Pedidos</a>
                    <a class="btn btn-primary btn-block text-white text-center" href="/">Página home</a>
				</div>
			</div>
		</div>
	</section>
	<!--/ End Checkout -->