		<!-- Breadcrumbs -->
		<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="bread-inner">
							<ul class="bread-list">
								<li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
								<li class="active"><a href="blog-single.html">Checkout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Breadcrumbs -->
				
		<!-- Start Checkout -->
		<section class="shop checkout section">
			<div class="container">
				<div class="row"> 
					<div class="col-lg-8 col-12">
						<div class="checkout-form">
							<h2>Informe os dados do cartão</h2>
							<br/>
							<!-- Form -->
							<form class="form" method="post" action="#">
								<div class="row">
									<div class="col-lg-12 col-md-6 col-12">
										<div class="form-group">
											<label>Número do cartão<span>*</span></label>
											<input type="text" name="n-cartao" placeholder="" required="required">
										</div>
									</div>
									<div class="col-lg-3 col-md-6 col-12">
										<div class="form-group">
											<label>Validade<span>*</span></label>
											<input type="text" name="validade" placeholder="MM/AA" required="required">
										</div>
									</div>
									<div class="col-lg-3 col-md-6 col-12">
										<div class="form-group">
											<label>Código de segurança<span>*</span></label>
											<input type="text" name="cod-seg" placeholder="CVV" required="required">
										</div>
									</div>
									<div class="col-lg-12 col-md-6 col-12">
										<div class="form-group">
											<label>Nome completo<span>*</span></label>
											<input type="text" name="nome" placeholder="" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>CPF<span>*</span></label>
											<input type="text" name="cpf" placeholder="" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Telefone<span>*</span></label>
											<input type="text" name="cpf" placeholder="" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-12">
										<div class="form-group">
											<label>Data de nascimento<span>*</span></label>
											<input type="date" name="nascimento" placeholder="" required="required">
										</div>
									</div>
									
									
								</div>
							</form>
							<!--/ End Form -->
						</div>
					</div>
					<div class="col-lg-4 col-12">
						<div class="order-details">
							<!-- Order Widget -->
							<div class="single-widget">
								<h2>Total carrinho</h2>
								<div class="content">
								<?php foreach($this->view->total_carrinho as $id_item => $item){ ?>
									<ul>
										<li>Subtotal<span>R$ <?= $item['total_carrinho'] ?></span></li>
										<li>Frete<span>R$ <?= $item['frete'] ?></span></li>
										<li class="last">Total<span>R$ <?= $item['total'] ?></span></li>
									</ul>
								<?php } ?>
								</div>
							</div>
							<!--/ End Order Widget -->
				
							<!-- Payment Method Widget -->
							<div class="single-widget payement">
								<div class="content">
									<img src="images/payment-method.png" alt="#">
								</div>
							</div>
							<!--/ End Payment Method Widget -->
							<!-- Button Widget -->
							<div class="single-widget get-button">
								<div class="content">
									<div class="button">
										<a href="/gera_pedido" class="btn">Efetuar compra</a>
									</div>
								</div>
							</div>
							<!--/ End Button Widget -->
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--/ End Checkout -->
		
		