<!-- Breadcrumbs -->
    <div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
							<li class="active"><a href="#">Minha conta</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->

    <!-- Shopping Cart -->
	<div class="shopping-cart section">
		<div class="container container-user">
        
			<header class="header shop header-user">
				<div class="header-inner">
					<div class="container">
						<div class="cat-nav-head">
							<div class="row">
								<div class="col-lg-9 col-12">
									<div class="menu-area">
										<!-- Main Menu -->
										<nav class="navbar navbar-expand-lg">
											<div class="navbar-collapse">	
												<div class="nav-inner">	
													<ul class="nav main-menu menu navbar-nav">
														<li class="active"><a href="/pagina_usuario">Minha conta</a></li>																			
														<li><a href="/pedido_usuario">Meus pedidos</a></li>
														<li><a href="/endereco_usuario">Endereços cadastrados</a></li>
													</ul>
												</div>
											</div>
										</nav>
										<!--/ End Main Menu -->	
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</header>
			<!--/ End Header Inner -->
			<section class="pagina-usuario">
				<div class="user-title">
					<h4>Detalhes da sua conta:</h4>
				</div>

				<div class="user-info">
					<p>Thiago Augusto</p>
					<p>thiagoalves008@gmail.com</p>
					<div class="bnt-user">
						<a href="#" class="bnt-user-edit">Editar</a>
						<a href="#" class="bnt-user-edit-senha">Mudar senha</a>
					</div>
					<div style="clear: both"></div>
				</div>

				<div class="user-info">
					<h5>Endereço padrão:</h5>
					<p>Thiago Augusto</p>
					<p>Rua santo violin</p>
					<p>Eldorado</p>
					<p>343</p>
					<p>Casa verde</p>
					<p>Ibiporã, Parana, 86200-000</p>
					<p>Brasil</p>
					<p>Telelefone: (43)9996-50307</p>
				</div>
				
			</section>

			

        </div>
    </div>