<!-- Breadcrumbs -->
<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="bread-inner">
						<ul class="bread-list">
							<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
							<li class="active"><a href="#">Minha conta</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->

    <!-- Shopping Cart -->
	<div class="shopping-cart section">
		<div class="container container-user">
        
			<header class="header shop header-user">
				<div class="header-inner">
					<div class="container">
						<div class="cat-nav-head">
							<div class="row">
								<div class="col-lg-9 col-12">
									<div class="menu-area">
										<!-- Main Menu -->
										<nav class="navbar navbar-expand-lg">
											<div class="navbar-collapse">	
												<div class="nav-inner">	
													<ul class="nav main-menu menu navbar-nav">
														<li><a href="/pagina_usuario">Minha conta</a></li>																			
														<li class="active"><a href="/pedido_usuario">Meus pedidos</a></li>
														<li><a href="/endereco_usuario">Endereços cadastrados</a></li>
													</ul>
												</div>
											</div>
										</nav>
										<!--/ End Main Menu -->	
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</header>
			<!--/ End Header Inner -->
			<section class="pagina-usuario">
				<div class="user-title">
					<h4>Pedidos:</h4>
				</div>
				
				<div class="table-pedido-usuario">
					<table>
						<tr>
							<th>Pedido</th>
							<th>Data</th>
							<th>Enviar para</th>
							<th>Total</th>
							<th>Status</th>
							<th>Ação</th>
						</tr>
						
						<?php foreach($this->view->getPedido as $id_item => $item){ 
							$date = new DateTime($item['data']);
							$data = $date->format('d/m/Y');
						?>	
						
						<tr>
							<td><?= $item['id'] ?></td>
							<td><?= $data ?></td>
							<td><?= $item['nome'].' '.$item['sobrenome'] ?></td>
							<td><?= $item['total'] ?></td>
							<td><?= $item['status'] ?></td>
							<td><a class="ver-pedido" href="/itens_pedido?pedido=<?= $item['id'] ?>"><span>Ver pedido</span></a></td>
							
						</tr>
						
						<?php } ?>	
					</table>
				</div>

				
				
			</section>

			

        </div>
    </div>